"""Canonical exported MCP tool registry."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from mikrus_mcp.tool_mikrus import (
    assign_domain,
    boost_server,
    describe_mikrus_capabilities,
    get_cloud,
    get_db_info,
    get_log_by_id,
    get_logs,
    get_ports,
    get_server_info,
    get_server_stats,
    list_configured_servers,
    list_servers,
    restart_server,
)
from mikrus_mcp.tool_system import (
    analyze_disk,
    cancel_program,
    change_service_state,
    check_port,
    cron_list,
    cron_remove,
    cron_upsert,
    docker_recreate_apply,
    docker_recreate_plan,
    docker_runtime_snapshot,
    execute_program,
    file_patch_atomic,
    find_system_errors,
    get_docker_logs,
    get_docker_stats,
    get_journal_logs,
    get_memory_info,
    get_network_info,
    get_process_tree,
    get_program_result,
    get_program_status,
    get_service_status,
    list_directory,
    list_docker_containers,
    list_processes,
    read_file,
    remote_job_cancel,
    remote_job_output,
    remote_job_result,
    remote_job_start,
    remote_job_status,
    remote_job_wait,
    search_in_files,
    search_journal_logs,
    service_wait,
    start_program,
    tail_file,
    terminate_process,
    update_system,
    write_file,
)

_TOOL_FUNCTIONS = (
    describe_mikrus_capabilities,
    list_configured_servers,
    get_server_info,
    list_servers,
    get_server_stats,
    restart_server,
    get_logs,
    get_log_by_id,
    boost_server,
    get_db_info,
    get_ports,
    get_cloud,
    assign_domain,
    read_file,
    write_file,
    get_service_status,
    change_service_state,
    analyze_disk,
    check_port,
    list_processes,
    terminate_process,
    update_system,
    list_directory,
    tail_file,
    search_in_files,
    get_memory_info,
    get_network_info,
    get_process_tree,
    list_docker_containers,
    get_docker_logs,
    get_docker_stats,
    get_journal_logs,
    find_system_errors,
    search_journal_logs,
    execute_program,
    start_program,
    get_program_status,
    get_program_result,
    cancel_program,
    remote_job_start,
    remote_job_status,
    remote_job_wait,
    remote_job_result,
    remote_job_output,
    remote_job_cancel,
    file_patch_atomic,
    cron_list,
    cron_upsert,
    cron_remove,
    docker_runtime_snapshot,
    docker_recreate_plan,
    docker_recreate_apply,
    service_wait,
)

TOOL_FUNCTIONS: dict[str, Callable[..., Any]] = {
    function.__name__: function for function in _TOOL_FUNCTIONS
}
