"""Single Source of Truth for all configuration defaults.

Every module MUST import defaults from this file.
No other file MAY define its own defaults for these values.
"""

import os
from typing import Any, Final

# API configuration
MIKRUS_API_URL = os.getenv("MIKRUS_API_URL", "https://api.mikr.us")

# Timeouts (seconds)
DEFAULT_HTTP_TIMEOUT: Final = 10.0
EXEC_HTTP_TIMEOUT: Final = 65.0
SSH_DEFAULT_TIMEOUT: Final = 30

# Logging
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

# Validation limits
MAX_TAIL_LINES: Final = 500
MAX_JOURNAL_LINES: Final = 500
MAX_SEARCH_RESULTS: Final = 100
MAX_GREP_HOURS: Final = 24
MAX_WRITE_SIZE: Final = 100_000

# Service actions
SERVICE_ACTIONS: Final = frozenset(
    {
        "status",
        "start",
        "stop",
        "restart",
        "enable",
        "disable",
        "is-active",
        "is-enabled",
    }
)

# Process actions
PROCESS_ACTIONS: Final = frozenset({"list", "kill"})

# Tool version — injected into every response _meta envelope
TOOLS_VERSION: Final = "1.0.0"

# Tool manifests — machine-readable capability metadata (L2+)
# Every registered tool MUST have a manifest entry.
TOOL_MANIFESTS: dict[str, dict[str, Any]] = {
    "get_server_info": {
        "name": "get_server_info",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "eventually-consistent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "execute_command": {
        "name": "execute_command",
        "version": "1.0.0",
        "risk": "DANGEROUS",
        "side_effects": "write",
        "idempotent": False,
        "retryable": False,
        "concurrent_safe": False,
        "timeout_ms": 60000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "slow",
        "cost": "expensive",
    },
    "restart_server": {
        "name": "restart_server",
        "version": "1.0.0",
        "risk": "DESTRUCTIVE",
        "side_effects": "destructive",
        "idempotent": False,
        "retryable": False,
        "concurrent_safe": False,
        "timeout_ms": 120000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "slow",
        "cost": "expensive",
    },
    "get_db_info": {
        "name": "get_db_info",
        "version": "1.0.0",
        "risk": "SENSITIVE",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "read_file": {
        "name": "read_file",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "list_servers": {
        "name": "list_servers",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "eventually-consistent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "get_server_stats": {
        "name": "get_server_stats",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "eventually-consistent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "get_logs": {
        "name": "get_logs",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "eventually-consistent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "get_log_by_id": {
        "name": "get_log_by_id",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "eventually-consistent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "boost_server": {
        "name": "boost_server",
        "version": "1.0.0",
        "risk": "WRITE",
        "side_effects": "write",
        "idempotent": False,
        "retryable": False,
        "concurrent_safe": True,
        "timeout_ms": 10000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "get_ports": {
        "name": "get_ports",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "eventually-consistent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "get_cloud": {
        "name": "get_cloud",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "eventually-consistent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "assign_domain": {
        "name": "assign_domain",
        "version": "1.0.0",
        "risk": "WRITE",
        "side_effects": "write",
        "idempotent": False,
        "retryable": False,
        "concurrent_safe": True,
        "timeout_ms": 10000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "write_file": {
        "name": "write_file",
        "version": "1.0.0",
        "risk": "WRITE",
        "side_effects": "write",
        "idempotent": False,
        "retryable": False,
        "concurrent_safe": False,
        "timeout_ms": 10000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "moderate",
    },
    "manage_service": {
        "name": "manage_service",
        "version": "1.0.0",
        "risk": "WRITE",
        "side_effects": "write",
        "idempotent": False,
        "retryable": False,
        "concurrent_safe": False,
        "timeout_ms": 10000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "fast",
        "cost": "cheap",
    },
    "analyze_disk": {
        "name": "analyze_disk",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 15000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "moderate",
    },
    "check_port": {
        "name": "check_port",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "fast",
        "cost": "cheap",
    },
    "manage_process": {
        "name": "manage_process",
        "version": "1.0.0",
        "risk": "DESTRUCTIVE",
        "side_effects": "destructive",
        "idempotent": False,
        "retryable": False,
        "concurrent_safe": False,
        "timeout_ms": 10000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "fast",
        "cost": "cheap",
    },
    "update_system": {
        "name": "update_system",
        "version": "1.0.0",
        "risk": "WRITE",
        "side_effects": "write",
        "idempotent": False,
        "retryable": False,
        "concurrent_safe": False,
        "timeout_ms": 120000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "slow",
        "cost": "expensive",
    },
    "list_directory": {
        "name": "list_directory",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "fast",
        "cost": "cheap",
    },
    "tail_file": {
        "name": "tail_file",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "fast",
        "cost": "cheap",
    },
    "search_in_files": {
        "name": "search_in_files",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 30000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "slow",
        "cost": "moderate",
    },
    "get_memory_info": {
        "name": "get_memory_info",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "fast",
        "cost": "cheap",
    },
    "get_network_info": {
        "name": "get_network_info",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "fast",
        "cost": "cheap",
    },
    "get_process_tree": {
        "name": "get_process_tree",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 5000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "fast",
        "cost": "cheap",
    },
    "list_docker_containers": {
        "name": "list_docker_containers",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 10000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "get_docker_logs": {
        "name": "get_docker_logs",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 10000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "get_docker_stats": {
        "name": "get_docker_stats",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 10000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "cheap",
    },
    "get_journal_logs": {
        "name": "get_journal_logs",
        "version": "1.0.0",
        "risk": "SENSITIVE",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 10000,
        "requires_confirmation": True,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "moderate",
    },
    "find_system_errors": {
        "name": "find_system_errors",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 15000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "moderate",
    },
    "search_journal_logs": {
        "name": "search_journal_logs",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 15000,
        "requires_confirmation": False,
        "determinism": "env-dependent",
        "latency": "moderate",
        "cost": "moderate",
    },
    "list_configured_servers": {
        "name": "list_configured_servers",
        "version": "1.0.0",
        "risk": "READ",
        "side_effects": "none",
        "idempotent": True,
        "retryable": True,
        "concurrent_safe": True,
        "timeout_ms": 1000,
        "requires_confirmation": False,
        "determinism": "deterministic",
        "latency": "instant",
        "cost": "cheap",
    },
}
