"""Backend client protocol and target factory."""

from __future__ import annotations

from typing import Any, Protocol, cast

from mikrus_mcp.clients.mikrus import MikrusClient
from mikrus_mcp.clients.ssh import SshClient
from mikrus_mcp.config import TargetConfig


class Client(Protocol):
    stable_identity: str

    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def get_server_info(self) -> Any: ...
    async def list_servers(self) -> Any: ...
    async def get_server_stats(self) -> Any: ...
    async def restart_server(self) -> Any: ...
    async def get_logs(self) -> Any: ...
    async def get_log_by_id(self, log_id: str) -> Any: ...
    async def boost_server(self) -> Any: ...
    async def get_db_info(self) -> Any: ...
    async def get_ports(self) -> Any: ...
    async def get_cloud(self) -> Any: ...
    async def assign_domain(self, port: str, domain: str) -> Any: ...
    async def read_file(self, path: str) -> Any: ...
    async def write_file(self, path: str, content: str) -> Any: ...
    async def get_service_status(self, name: str) -> Any: ...
    async def change_service_state(self, name: str, action: str) -> Any: ...
    async def analyze_disk(self, path: str = "/") -> Any: ...
    async def check_port(self, port: str) -> Any: ...
    async def list_processes(self) -> Any: ...
    async def terminate_process(self, target: str) -> Any: ...
    async def update_system(self) -> Any: ...
    async def list_directory(self, path: str) -> Any: ...
    async def tail_file(self, path: str, lines: int = 50) -> Any: ...
    async def search_in_files(self, path: str, pattern: str) -> Any: ...
    async def get_memory_info(self) -> Any: ...
    async def get_network_info(self) -> Any: ...
    async def get_process_tree(self) -> Any: ...
    async def list_docker_containers(self) -> Any: ...
    async def get_docker_logs(self, container: str, lines: int = 50) -> Any: ...
    async def get_docker_stats(self) -> Any: ...
    async def get_journal_logs(self, unit: str, lines: int = 50) -> Any: ...
    async def find_system_errors(self, hours: int = 1) -> Any: ...
    async def search_journal_logs(self, term: str, lines: int = 50) -> Any: ...
    async def execute_program(
        self,
        executable: str,
        argv: list[str],
        cwd: str | None = None,
        stdin: str | None = None,
    ) -> Any: ...
    async def remote_job_start(
        self,
        *,
        job_id: str,
        request_digest: str,
        executable: str,
        argv: list[str],
        cwd: str | None,
        stdin: str | None,
    ) -> Any: ...
    async def remote_job_status(self, *, job_id: str) -> Any: ...
    async def remote_job_wait(self, *, job_id: str, timeout_seconds: float) -> Any: ...
    async def remote_job_result(self, *, job_id: str) -> Any: ...
    async def remote_job_output(
        self, *, job_id: str, stream: str, offset: int, max_bytes: int
    ) -> Any: ...
    async def remote_job_cancel(self, *, job_id: str, reason: str) -> Any: ...
    async def file_patch_atomic(
        self, *, path: str, expected_digest: str, content_b64: str
    ) -> Any: ...
    async def cron_read(self) -> Any: ...
    async def cron_install(self, *, expected_hash: str, new_text: str) -> Any: ...
    async def docker_ps_filter(self, *, service: str, project: str | None = None) -> Any: ...
    async def docker_inspect(self, ids: list[str]) -> Any: ...
    async def docker_compose_config(self, *, project: str, files: list[str]) -> Any: ...
    async def docker_image_inspect(self, image: str) -> Any: ...
    async def docker_compose_up(self, *, project: str, files: list[str], service: str) -> Any: ...
    async def docker_service_wait(
        self, *, container_id: str, readiness: str, timeout_seconds: float
    ) -> Any: ...


def build_client(config: TargetConfig) -> Client:
    if config.type == "mikrus":
        if not (config.api_url and config.api_key and config.server_id):
            raise ValueError("mikrus target is missing validated API configuration")
        return MikrusClient(config.api_url, config.api_key, config.server_id)
    return cast(Client, SshClient(config))
