"""Backend client protocol and target factory."""

from __future__ import annotations

from typing import Any, Protocol

from mikrus_mcp.clients.mikrus import MikrusClient
from mikrus_mcp.clients.ssh import SshClient
from mikrus_mcp.config import TargetConfig


class Client(Protocol):
    stable_identity: str

    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def get_server_info(self) -> Any: ...
    async def list_servers(self) -> Any: ...
    async def get_server_stats(self) -> Any: ...
    async def restart_server(self) -> Any: ...
    async def get_logs(self) -> Any: ...
    async def get_log_by_id(self, log_id: str) -> Any: ...
    async def boost_server(self) -> Any: ...
    async def get_db_info(self) -> Any: ...
    async def get_ports(self) -> Any: ...
    async def get_cloud(self) -> Any: ...
    async def assign_domain(self, port: str, domain: str) -> Any: ...
    async def execute_command(self, command: str) -> Any: ...
    async def read_file(self, path: str) -> Any: ...
    async def write_file(self, path: str, content: str) -> Any: ...
    async def get_service_status(self, name: str) -> Any: ...
    async def change_service_state(self, name: str, action: str) -> Any: ...
    async def analyze_disk(self, path: str = "/") -> Any: ...
    async def check_port(self, port: str) -> Any: ...
    async def list_processes(self) -> Any: ...
    async def terminate_process(self, target: str) -> Any: ...
    async def update_system(self) -> Any: ...
    async def list_directory(self, path: str) -> Any: ...
    async def tail_file(self, path: str, lines: int = 50) -> Any: ...
    async def search_in_files(self, path: str, pattern: str) -> Any: ...
    async def get_memory_info(self) -> Any: ...
    async def get_network_info(self) -> Any: ...
    async def get_process_tree(self) -> Any: ...
    async def list_docker_containers(self) -> Any: ...
    async def get_docker_logs(self, container: str, lines: int = 50) -> Any: ...
    async def get_docker_stats(self) -> Any: ...
    async def get_journal_logs(self, unit: str, lines: int = 50) -> Any: ...
    async def find_system_errors(self, hours: int = 1) -> Any: ...
    async def search_journal_logs(self, term: str, lines: int = 50) -> Any: ...


def build_client(config: TargetConfig) -> Client:
    if config.type == "mikrus":
        assert config.api_url and config.api_key and config.server_id
        return MikrusClient(config.api_url, config.api_key, config.server_id)
    return SshClient(config)
